server {
  listen 4201;
  root /srv/cedar/cedar-workspace/app;

  location = /index.html {
    add_header Cache-Control "no-store" always;
  }
  location ^~ /config/ {
    add_header Cache-Control "no-store" always;
    try_files $uri =404;
  }
  location ~* \.(html|css)$ {
    add_header Cache-Control "no-cache" always;
  }
  location / {
    try_files $uri /index.html;
  }

  error_log /log/nginx-error.log warn;
  access_log /log/nginx-access.log combined;
}
